name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet build -c Release --no-restore

      - name: Upload MQTTPlugin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MQTTPlugin-${{ github.sha }}
          path: MqttPlugin.Launchbox.Core/bin/Release/net9.0/MQTTPlugin/
          if-no-files-found: error
          retention-days: 90
