name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 1.0.0)"
        required: true
        type: string

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet build -c Release --no-restore

      - name: Create release zip
        run: |
          cd MqttPlugin.Launchbox.Core/bin/Release/net9.0-windows/MQTTPlugin
          Compress-Archive -Path * -DestinationPath ../../../../../launchbox2mqtt-v${{ inputs.version }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          files: launchbox2mqtt-v${{ inputs.version }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
